name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install Depdendencies & Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: build
